apiVersion: v1
kind: Service
metadata:
  name: surf-app
  labels:
    app: surf-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: surf-app

